# Generated by Django 5.2.4 on 2025-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.CharField()),
                ('foods', models.JSONField()),
                ('veggy', models.BooleanField(default=False)),
            ],
        ),
    ]
